// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: pix.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixRequest) Reset() {
	*x = PixRequest{}
	mi := &file_pix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixRequest) ProtoMessage() {}

func (x *PixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixRequest.ProtoReflect.Descriptor instead.
func (*PixRequest) Descriptor() ([]byte, []int) {
	return file_pix_proto_rawDescGZIP(), []int{0}
}

func (x *PixRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PixCreateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixCreateKeyRequest) Reset() {
	*x = PixCreateKeyRequest{}
	mi := &file_pix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixCreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixCreateKeyRequest) ProtoMessage() {}

func (x *PixCreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixCreateKeyRequest.ProtoReflect.Descriptor instead.
func (*PixCreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_pix_proto_rawDescGZIP(), []int{1}
}

func (x *PixCreateKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PixCreateKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PixCreateKeyRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type PixKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Exists        bool                   `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixKeyResponse) Reset() {
	*x = PixKeyResponse{}
	mi := &file_pix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixKeyResponse) ProtoMessage() {}

func (x *PixKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixKeyResponse.ProtoReflect.Descriptor instead.
func (*PixKeyResponse) Descriptor() ([]byte, []int) {
	return file_pix_proto_rawDescGZIP(), []int{2}
}

func (x *PixKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PixKeyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PixKeyResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *PixKeyResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type PixCreateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixCreateKeyResponse) Reset() {
	*x = PixCreateKeyResponse{}
	mi := &file_pix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixCreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixCreateKeyResponse) ProtoMessage() {}

func (x *PixCreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixCreateKeyResponse.ProtoReflect.Descriptor instead.
func (*PixCreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_pix_proto_rawDescGZIP(), []int{3}
}

func (x *PixCreateKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_pix_proto protoreflect.FileDescriptor

const file_pix_proto_rawDesc = "" +
	"\n" +
	"\tpix.proto\x12\n" +
	"pix_ledger\"\x1e\n" +
	"\n" +
	"PixRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"T\n" +
	"\x13PixCreateKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"k\n" +
	"\x0ePixKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x16\n" +
	"\x06exists\x18\x04 \x01(\bR\x06exists\"(\n" +
	"\x14PixCreateKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2\x9b\x01\n" +
	"\n" +
	"PixService\x12=\n" +
	"\aFindKey\x12\x16.pix_ledger.PixRequest\x1a\x1a.pix_ledger.PixKeyResponse\x12N\n" +
	"\tCreateKey\x12\x1f.pix_ledger.PixCreateKeyRequest\x1a .pix_ledger.PixCreateKeyResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_pix_proto_rawDescOnce sync.Once
	file_pix_proto_rawDescData []byte
)

func file_pix_proto_rawDescGZIP() []byte {
	file_pix_proto_rawDescOnce.Do(func() {
		file_pix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pix_proto_rawDesc), len(file_pix_proto_rawDesc)))
	})
	return file_pix_proto_rawDescData
}

var file_pix_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pix_proto_goTypes = []any{
	(*PixRequest)(nil),           // 0: pix_ledger.PixRequest
	(*PixCreateKeyRequest)(nil),  // 1: pix_ledger.PixCreateKeyRequest
	(*PixKeyResponse)(nil),       // 2: pix_ledger.PixKeyResponse
	(*PixCreateKeyResponse)(nil), // 3: pix_ledger.PixCreateKeyResponse
}
var file_pix_proto_depIdxs = []int32{
	0, // 0: pix_ledger.PixService.FindKey:input_type -> pix_ledger.PixRequest
	1, // 1: pix_ledger.PixService.CreateKey:input_type -> pix_ledger.PixCreateKeyRequest
	2, // 2: pix_ledger.PixService.FindKey:output_type -> pix_ledger.PixKeyResponse
	3, // 3: pix_ledger.PixService.CreateKey:output_type -> pix_ledger.PixCreateKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pix_proto_init() }
func file_pix_proto_init() {
	if File_pix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pix_proto_rawDesc), len(file_pix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pix_proto_goTypes,
		DependencyIndexes: file_pix_proto_depIdxs,
		MessageInfos:      file_pix_proto_msgTypes,
	}.Build()
	File_pix_proto = out.File
	file_pix_proto_goTypes = nil
	file_pix_proto_depIdxs = nil
}
