// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: pix.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PixService_FindKey_FullMethodName   = "/pix_ledger.PixService/FindKey"
	PixService_CreateKey_FullMethodName = "/pix_ledger.PixService/CreateKey"
)

// PixServiceClient is the client API for PixService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PixServiceClient interface {
	FindKey(ctx context.Context, in *PixRequest, opts ...grpc.CallOption) (*PixKeyResponse, error)
	CreateKey(ctx context.Context, in *PixCreateKeyRequest, opts ...grpc.CallOption) (*PixCreateKeyResponse, error)
}

type pixServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPixServiceClient(cc grpc.ClientConnInterface) PixServiceClient {
	return &pixServiceClient{cc}
}

func (c *pixServiceClient) FindKey(ctx context.Context, in *PixRequest, opts ...grpc.CallOption) (*PixKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PixKeyResponse)
	err := c.cc.Invoke(ctx, PixService_FindKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pixServiceClient) CreateKey(ctx context.Context, in *PixCreateKeyRequest, opts ...grpc.CallOption) (*PixCreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PixCreateKeyResponse)
	err := c.cc.Invoke(ctx, PixService_CreateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PixServiceServer is the server API for PixService service.
// All implementations must embed UnimplementedPixServiceServer
// for forward compatibility.
type PixServiceServer interface {
	FindKey(context.Context, *PixRequest) (*PixKeyResponse, error)
	CreateKey(context.Context, *PixCreateKeyRequest) (*PixCreateKeyResponse, error)
	mustEmbedUnimplementedPixServiceServer()
}

// UnimplementedPixServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPixServiceServer struct{}

func (UnimplementedPixServiceServer) FindKey(context.Context, *PixRequest) (*PixKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindKey not implemented")
}
func (UnimplementedPixServiceServer) CreateKey(context.Context, *PixCreateKeyRequest) (*PixCreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKey not implemented")
}
func (UnimplementedPixServiceServer) mustEmbedUnimplementedPixServiceServer() {}
func (UnimplementedPixServiceServer) testEmbeddedByValue()                    {}

// UnsafePixServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PixServiceServer will
// result in compilation errors.
type UnsafePixServiceServer interface {
	mustEmbedUnimplementedPixServiceServer()
}

func RegisterPixServiceServer(s grpc.ServiceRegistrar, srv PixServiceServer) {
	// If the following call panics, it indicates UnimplementedPixServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PixService_ServiceDesc, srv)
}

func _PixService_FindKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixServiceServer).FindKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PixService_FindKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixServiceServer).FindKey(ctx, req.(*PixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PixService_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PixCreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixServiceServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PixService_CreateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixServiceServer).CreateKey(ctx, req.(*PixCreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PixService_ServiceDesc is the grpc.ServiceDesc for PixService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PixService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pix_ledger.PixService",
	HandlerType: (*PixServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindKey",
			Handler:    _PixService_FindKey_Handler,
		},
		{
			MethodName: "CreateKey",
			Handler:    _PixService_CreateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pix.proto",
}
